### ISSUE TITLE
[BUG] when use "sortInventory" game

### ISSUE THREAD

**Issue by qianyue996** [sakura-ryoko/itemscroller#10]
In the server, when I open the shulker box in the backpack using the "quick shulker" module and use the R key to tidy up, the game is not responding, and the jdk is sending data to the server at a high rate, which seems to be a data loop.
[latest.log](https://github.com/user-attachments/files/16429390/latest.log)

**Comment by wendavid552** [comment]
Are you using `quickshulker` of the version here https://github.com/Haocen2004/quickshulker/releases ?

I try reproduce it, my game is responding and it just sending data by like ~100 packets I/O.

And could you provide the logs from your client?

**Comment by qianyue996** [comment]
> 您使用的`quickshulker`是此处的版本https://github.com/Haocen2004/quickshulker/releases吗？
> 
> 我尝试重现它，我的游戏正在响应，它只是通过大约 100 个数据包 I/O 发送数据。
> 
> 您能提供来自客户的日志吗？

Yes, I am using the version `1.4.5`. Do you want this log? I may not understand.
[hmcl.log](https://github.com/user-attachments/files/16436206/hmcl.log)

**Comment by qianyue996** [comment]
> Are you using `quickshulker` of the version here https://github.com/Haocen2004/quickshulker/releases ?
> 
> I try reproduce it, my game is responding and it just sending data by like ~100 packets I/O.
> 
> And could you provide the logs from your client?

Yes, I am using the version 1.4.5. Do you want this log? I may not understand.
[hmcl.log](https://github.com/user-attachments/files/16436218/hmcl.log)

**Comment by LuoliiQaQ** [comment]
I also have this bug, after using it, MC does not respond and can only be forcibly closed

**Comment by Liu7671** [comment]
不能使用子区块合成进行高速合成活塞

**Comment by wendavid552** [comment]
> > Are you using `quickshulker` of the version here [Haocen2004/quickshulker/releases](https://github.com/Haocen2004/quickshulker/releases) ?
> > I try reproduce it, my game is responding and it just sending data by like ~100 packets I/O.
> > And could you provide the logs from your client?
> 
> Yes, I am using the version 1.4.5. Do you want this log? I may not understand. [hmcl.log](https://github.com/user-attachments/files/16436218/hmcl.log)

Actually I need logs/latest.log under Minecraft folder. You could try reproduce your operation, close the game, and send me latest.log.

You could also find the logs folder here in HMCL:
![image](https://github.com/user-attachments/assets/7756a0c5-e73c-49fb-93b4-66e00049db8c)
and then upload the latest.log.

实际上我需要的是minecraft游戏文件夹下的logs/latest.log。你可以先开一下游戏，复现一下操作，关掉游戏，然后把latest.log发给我。

你也可以按照上面那张图的指示，打开我说的logs文件夹，在这下面找到latest.log。

**Comment by qianyue996** [comment]
> > > Are you using `quickshulker` of the version here [Haocen2004/quickshulker/releases](https://github.com/Haocen2004/quickshulker/releases) ?
> > > I try reproduce it, my game is responding and it just sending data by like ~100 packets I/O.
> > > And could you provide the logs from your client?
> > 
> > 
> > Yes, I am using the version 1.4.5. Do you want this log? I may not understand. [hmcl.log](https://github.com/user-attachments/files/16436218/hmcl.log)
> 
> Actually I need logs/latest.log under Minecraft folder. You could try reproduce your operation, close the game, and send me latest.log.
> 
> You could also find the logs folder here in HMCL: ![image](https://private-user-images.githubusercontent.com/72400592/357790219-7756a0c5-e73c-49fb-93b4-66e00049db8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxOTk5MzksIm5iZiI6MTcyNDE5OTYzOSwicGF0aCI6Ii83MjQwMDU5Mi8zNTc3OTAyMTktNzc1NmEwYzUtZTczYy00OWZiLTkzYjQtNjZlMDAwNDlkYjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAwMjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZWNhMzkwMTZhNDFkMWI0ODExMzZhNzM4MjQ4OTJhMTI2MzlmMGIxMTNlYjBlMDg4OTVlZTllM2M1MWYzZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xiHL4YSf6krWkuGjDzhQar4FcxH2GUtuldKVB8kHbDg) and then upload the latest.log.
> 
> 实际上我需要的是minecraft游戏文件夹下的logs/latest.log。你可以先开一下游戏，复现一下操作，关掉游戏，然后把latest.log发给我。
> 
> 你也可以按照上面那张图的指示，打开我说的logs文件夹，在这下面找到latest.log。

emm 我好久没开客户端了，不知道这个对不对，是你说的在logs/latest.log这个文件，服务端也下线了，或许有用吧，如果没有我再尝试复现操作看看
[latest.log](https://github.com/user-attachments/files/16683778/latest.log)

**Comment by wendavid552** [comment]
> emm 我好久没开客户端了，不知道这个对不对，是你说的在logs/latest.log这个文件，服务端也下线了，或许有用吧，如果没有我再尝试复现操作看看 [latest.log](https://github.com/user-attachments/files/16683778/latest.log)

There's no relate information. 这个看着好像没有相关的问题。

**Comment by qianyue996** [comment]
> > emm 我好久没开客户端了，不知道这个对不对，是你说的在logs/latest.log这个文件，服务端也下线了，或许有用吧，如果没有我再尝试复现操作看看 [latest.log](https://github.com/user-attachments/files/16683778/latest.log)
> 
> There's no relate information. 这个看着好像没有相关的问题。

好的，现在我又出现问题了，我把这个latest.log发上来。
[latest.log](https://github.com/user-attachments/files/16738560/latest.log)

**Comment by sakura-ryoko** [comment]
```
[09:40:34] [REI-ReloadPlugins/ERROR]: [REI] Failed to collect creative tab: net.minecraft.class_1761@34236fa7
java.lang.IllegalStateException: Registry minecraft:banner_pattern not found
	at net.minecraft.class_7225$class_7874.method_46763(class_7225.java:107) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_7225$class_7874.method_46762(class_7225.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_7706.method_51332(class_7706.java:1266) ~[client-intermediary.jar:?]
	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:56) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:195) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:156) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]

```
This is the "REI" mod trying to access an invalid World's Dynamic Registry Manager, perhaps.  Lithium had the same problem with Litematica, but I fixed that.  The Litematica Schematic World correctly returns a Dynamic Registry Manager object upon request; But other mods *SHOULD NOT* be referencing the Schematic World.

In fact, Litematica returns a valid object *BEFORE* the Vanilla Client World is even created, and is now even more reliable than the Vanilla `mc.world.getRegistryMananger()` method, even if `mc.world == null`

So, this seems to be a bug with "REI" .

**Comment by qianyue996** [comment]
> ```
> [09:40:34] [REI-ReloadPlugins/ERROR]: [REI] Failed to collect creative tab: net.minecraft.class_1761@34236fa7
> java.lang.IllegalStateException: Registry minecraft:banner_pattern not found
> 	at net.minecraft.class_7225$class_7874.method_46763(class_7225.java:107) ~[client-intermediary.jar:?]
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
> 	at net.minecraft.class_7225$class_7874.method_46762(class_7225.java:107) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_7706.method_51332(class_7706.java:1266) ~[client-intermediary.jar:?]
> 	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:56) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
> 	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:195) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
> 	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:156) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
> 	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
> 	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
> 	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-16.0.744-fabric.jar:?]
> ```
> 
> This is the "REI" mod trying to access an invalid World's Dynamic Registry Manager, perhaps. Lithium had the same problem with Litematica, but I fixed that. The Litematica Schematic World correctly returns a Dynamic Registry Manager object upon request; But other mods _SHOULD NOT_ be referencing the Schematic World.
> 
> In fact, Litematica returns a valid object _BEFORE_ the Vanilla Client World is even created, and is now even more reliable than the Vanilla `mc.world.getRegistryMananger()` method, even if `mc.world == null`
> 
> So, this seems to be a bug with "REI" .

>All right, but I have tried to exclude all mods and leave only the "itemscroller" mod, but this kind of error still occurred. If necessary, I can provide the log file later, but I'm sorry, my laptop is currently under repair and may take some time.

**Comment by LuoliiQaQ** [comment]
我的猜测是背包中有不可移动的东西比如潜影盒，按r后itemscroller会尝试将潜影盒放入潜影盒中，但是这种功能原版中本身就是不能将潜影盒放入潜影盒中的，所以itemscroller一直尝试将潜影盒放潜影盒里，造成了无限的数据发送导致mc无响应，这个无法移动不可移动的东西可能涉及范围非常广，比如插件服的一些类似的东西等等

**Comment by sakura-ryoko** [comment]
Additional fixes:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3
