### ISSUE TITLE
R键整理与GCA并用导致游戏卡死

### ISSUE THREAD

**Issue by Adogs1** [sakura-ryoko/itemscroller#12]
这是一个很早在ommc就出现的错误，在Bilibili古镇天开发的GCA carpet附加包中，它允许对假玩家右键打开他的背包，不仅可以快捷的取走物品，还可以通过点击原作者设计在背包的屏障方块占位符实现几个设定好的功能。之前与ommc一起使用时，对假人背包进行r键整理，物品确实会被整理，但同时屏障方块占位符也全都都会被点击一遍（存疑）。所以每次整理假人玩家的背包后，假人就会执行一些奇怪的手臂行为动作（占位符有：一直右键、间隔14gt左键、一直左键、切换假人快捷栏选中1~9、停止所有动作）。但使用ItemScroller的R键对假人玩家背包整理，它会直接导致游戏卡死（保持很久的未响应）

**Comment by wendavid552** [comment]
> Translation to the issue above: 
> gugle-carpet-addition enables you open the inventory of a fake player, and it adds some barrier item in the inventory, so when you click it, the fake player would switch to certain actions (e.g. attack, use, etc.). The latest `Sort Inventory` will click these items and thus stuck the game (client I think). This also issues in similar feature from `OMMC`.

Is there any issues from `OMMC` or `gugle-carpet-addition`? I would consider this as a bug from `gugle-carpet-addition` and this behaviour works as intended.

OMMC或者gca有没有相关的issue或者报告呢？从单纯整理来讲客户端应该没法识别这种占位方块是否需要整理。另外我认为这可能是一个gca的bug。

**Comment by wucy777** [comment]
> > 翻译到上面的问题：gugle-carpet-addition 可以让你打开一个假玩家的库存，并在库存中添加一些屏障物品，所以当你点击它时，假玩家会切换到某些操作（例如攻击、使用等）。最新的将单击这些项目，从而卡住游戏（我认为是客户端）。这在 中的类似功能中也存在问题。`Sort Inventory``OMMC`
> 
> 或 有任何问题吗？我认为这是一个错误，并且这种行为按预期工作。`OMMC``gugle-carpet-addition``gugle-carpet-addition`
> 
> OMMC或者gca有没有相关的issue或者报告呢？从单纯整理来讲客户端应该没法识别这种占位方块是否需要整理。另外我认为这可能是一个gca的bug。

但事实是有人还发现物品滚轮r整理其他mod提供的容器gui或原版盔甲槽位置也会导致游戏未响应

**Comment by wendavid552** [comment]
> > > 翻译到上面的问题：gugle-carpet-addition 可以让你打开一个假玩家的库存，并在库存中添加一些屏障物品，所以当你点击它时，假玩家会切换到某些操作（例如攻击、使用等）。最新的将单击这些项目，从而卡住游戏（我认为是客户端）。这在 中的类似功能中也存在问题。`` Sort Inventory``OMMC ``
> > 
> > 
> > 或 有任何问题吗？我认为这是一个错误，并且这种行为按预期工作。`` OMMC``gugle-carpet-addition``gugle-carpet-addition ``
> > OMMC或者gca有没有相关的issue或者报告呢？从单纯整理来讲客户端应该没法识别这种占位方块是否需要整理。另外我认为这可能是一个gca的bug。
> 
> 但事实是有人还发现物品滚轮r整理其他mod提供的容器gui或原版盔甲槽位置也会导致游戏未响应

确实有这种现象，主要的原因是这些容器有部分物品不给排序。在未来版本应该会考虑修复这个问题。

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.1 has the toggle to disable `sortInventory`

**Comment by sakura-ryoko** [comment]
Additional fixes:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3
