### ISSUE TITLE
[Suggestion] Sorting method

### ISSUE THREAD

**Issue by AkuaMoon** [sakura-ryoko/itemscroller#13]
Can you use the same sort method used by IPN to creative inventory.

(Translated by software)

**Comment by sakura-ryoko** [comment]
I don't know what IPN is, but for the Snapshot version, I just created a 'Creative Menu Category' sorting option, and along with Items by Name rather than Item ID.

**Comment by sakura-ryoko** [comment]
See the changes: https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.1

**Comment by sakura-ryoko** [comment]
Additional fixes:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3
