### ISSUE TITLE
R键整理导致游戏卡死

### ISSUE THREAD

**Issue by xjxiw** [sakura-ryoko/itemscroller#14]
鼠标指针移动到身上的副手槽位以及四个装备槽位时按R会导致游戏停止运行

**Comment by xjxiw** [comment]
mod版本为1.21-sakura.8

**Comment by xjxiw** [comment]
还有一个问题  快捷栏最后一格放潜影盒以外的物品不会被整理 （？）  以及测试视频链接https://www.bilibili.com/video/BV1bLpZetEzB/

**Comment by LuoliiQaQ** [comment]
对快捷潜影盒里的内容物进行r键整理后，我的世界没有响应，卡住了

**Comment by sakura-ryoko** [comment]
Additional fixes:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3
