### ISSUE TITLE
一键整理的问题

### ISSUE THREAD

**Issue by LuoliiQaQ** [sakura-ryoko/itemscroller#16]
对快捷潜影盒快捷打开潜影盒的gui后对着潜影盒内容物按一次r就无响应
打开背包后，找到潜影盒然后使用快捷潜影盒，然后对潜影盒内的内容物按一次R，软件就无响应
等待了五分钟都没反应，必须使用任务管理器才能强制退出
【原版r键是开光影，我把光影按键给改成其他的了 确定了其他的模组没有任何绑定r】
【我将r改成其他任何按键，也会发生同样的情况也就是无响应】

**Comment by LuoliiQaQ** [comment]
解决了 我的方法是
首先完全关闭我的世界游戏
然后找到.minecraft/confing文件夹内
找到quick开头的有关潜影盒的json文件以及itemscroller的json文件
启动游戏就好了
记得按键绑定那边光影的绑定按键是r（游戏本身默认）
这两个冲突 把光影的改成别的就解决了

**Comment by LuoliiQaQ** [comment]
您好，我发现bug还是存在，版本是Sakura8

**Comment by LuoliiQaQ** [comment]
[错误报告-2024-8-26_0.48.51.zip](https://github.com/user-attachments/files/16741244/-2024-8-26_0.48.51.zip)
这是我的错误报告

**Comment by fcsailboat** [comment]
不只是快捷潜影盒，整理GCA的假人背包也会无响应，并且如果是多人游戏，服务器也会明显卡顿，怀疑是GUI中有不可移动的物品

**Comment by sakura-ryoko** [comment]
> 对快捷潜影盒快捷打开潜影盒的gui后对着潜影盒内容物按一次r就无响应
> 打开背包后，找到潜影盒然后使用快捷潜影盒，然后对潜影盒内的内容物按一次R，软件就无响应
> 等待了五分钟都没反应，必须使用任务管理器才能强制退出
> 【原版r键是开光影，我把光影按键给改成其他的了 确定了其他的模组没有任何绑定r】
> 【我将r改成其他任何按键，也会发生同样的情况也就是无响应】

Google:
```
After opening the gui of the quick shulker box, press R once on the contents of the shulker box, and it will not respond. After opening the backpack, find the shulker box and use the quick shulker box, then press R once on the contents of the shulker box, and the software will not respond. I waited for five minutes and still didn't respond. I had to use the task manager to force quit. [The original R key is to open the light and shadow, I changed the light and shadow key to something else. I made sure that other modules have no binding to R] [I changed R to any other key, and the same situation will happen, that is, no response]
```

**Comment by sakura-ryoko** [comment]
> 不只是快捷潜影盒，整理GCA的假人背包也会无响应，并且如果是多人游戏，服务器也会明显卡顿，怀疑是GUI中有不可移动的物品

Google:
```
It's not just the quick shulker box. The GCA dummy backpack will also be unresponsive. If it's a multiplayer game, the server will also be obviously stuck. I suspect there are unmovable items in the GUI.
```

**Comment by sakura-ryoko** [comment]
This is a problem in the logs with "REI"
```
[00:46:08] [Render thread/WARN]: Do not use this method; its API is fundamentally broken.
[00:46:08] [Render thread/WARN]: Use of net.minecraft.class_5225.method_27494 detected.
```

The error does not say 'itemscroller'.  So, disable the itemscroller 'R' key if you wish to use these other mods.

**Comment by LuoliiQaQ** [comment]
您好，我删除了全部的模组，只保留itemscroller以及快捷潜影盒之后，进入服务器按r还是会崩溃

**Comment by LuoliiQaQ** [comment]
经过调查，我发现我的朋友以及遇到过的人都有这个视频中的情况，他无法生成崩溃日志，只是出现无响应只能通过任务管理器强制关闭程序，以及我只加入了itemscroller模组和快捷潜影盒模组以及一些前置开启游戏时，单人游戏测试了半小时，无论如何整理都不会崩溃，然后我寻找了5个服务器，无论如何整理潜影盒，只要我一按R键，立马就无响应，无响应后等待十分钟都无法主动退出软件程序生成错误日志报告，只能通过任务管理器强制退出软件程序，我的无响应是从快捷潜影盒中R键整理发现的，我的建议是Sakura请您去服务器中测试，因为这个bug只会在服务器中出现，单机是没有问题的，我以为是快捷潜影盒有问题，我换了另一个人fork的快捷潜影盒后发现无响应还是存在。

【物品滚轮itemscroller R一键整理潜影盒openjdk platform binary无响应-哔哩哔哩】 https://b23.tv/TWeEUZQ

这是相关的视频链接，我和他的情况一模一样

我的总结是 保留itemscroller和快捷潜影盒以及相关前置后，进入单机是没有这个bug的 但是进入服务器后这个bug会马上发生，无论是什么服务器，只要在潜影盒的gui里按r就无响应，我非常建议您可以查看一下我发的视频链接

**Comment by LuoliiQaQ** [comment]
![Uploading 1725408156529.png…]()

**Comment by LuoliiQaQ** [comment]
我又有了一个新的猜测
1.把潜影盒放在地上，放一些随便的东西都可以，然后重要的来了，背包携带一个潜影盒，空不空的都无所谓，然后退出背包gui，右键刚刚放在地上的潜影盒后，然后再整理一下潜影盒，就会无响应
结论:有可能是itemscroller的r键整理一直尝试把背包的潜影盒放进地上刚放的潜影盒里，原版是无论怎么样都不可以把潜影盒放进另一个潜影盒里，所以它一直尝试把潜影盒放进潜影盒里结果无限循环，导致无响应

如果是这样的话可能涉及的方面太多了，比如假人背包的一些东西，盔甲架栏，以及插件服的一些东西都是锁死的不可以移动，这样也会造成无响应，而且esc的按键控制，最下面的r是绑定的光影，有可能也会有按键冲突导致异常，我强烈建议修复此bug，它太严重了

**Comment by sakura-ryoko** [comment]
Sorry I cannot read Chinese without using Google Translate; but I have not experienced the problems that you are describing.   Try disabling `sortAssumeEmptyBoxStacks` and using the update:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.1

Also, with the new version, for Incompatible servers and incompatible mods, then just disable the feature using `sortInventoryToggle` .

**Comment by LuoliiQaQ** [comment]
Hello, after I disabled the option according to the method you said, I used it for a while, at first found it was OK, but after a long time, it began to not respond, how is this? The crash report cannot be brought up, and the program can only be forcibly terminated

**Comment by LuoliiQaQ** [comment]
I finally figured out what the problem is, and it has nothing to do with itemscroller itself, and nothing to do with the quick Shulker box


Assume that the contents of the shulker box are greater than the empty space in the backpack
For example, a shulker box has 10 different items
The player's backpack has 26 shulker boxes and 1 empty space (the player's backpack can carry 27 items, except for the shortcut bar).
Press R once and there's no response
But if there's more in the shulker box than there is in the backpack
For example, a shulker box contains only one item
The player's backpack has some empty space (must be greater than or equal to 1) and some shulker boxes
No matter how hard you press the r button, it won't crash

So, if the contents of the shulker are larger than the backpack space (everything except the Shulker is a Shulker), the item scroller will try to put the Shulker into the Shulker but will fail, resulting in an infinite loop
![Uploading IMG_20240914_085551.jpg…]()

**Comment by LuoliiQaQ** [comment]
Version 1.21 of the game

**Comment by sakura-ryoko** [comment]
Try this.
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3

**Comment by sakura-ryoko** [comment]
Try it with 1.21.3.
