### ISSUE TITLE
Sorting a Shulker Box with specific player inventory slots filled causes hotbar slots to move around

### ISSUE THREAD

**Issue by machasins** [sakura-ryoko/itemscroller#23]
A lot of weird things happen with shulkers when your inventory is in various states of fullness.

Firstly, if the player's hotbar does not have slot 9 filled, sorting a shulker box results in one of the items in the hotbar moving to the middle of the inventory (ie, from slot 8 of the hotbar to slot 9 of row 2 in the inventory).

![javaw_xosau0bovT](https://github.com/user-attachments/assets/64580230-49a8-4027-adbb-87b3d510cdf6)

Furthermore, if rows 1 and 2 of the inventory are full, hotbar slots will start moving into the shulker after every sort.

![javaw_xYLMVT5Cks](https://github.com/user-attachments/assets/259241bf-d310-4257-b29a-94ac50bebd10)

**Comment by sakura-ryoko** [comment]
Again,

Are you using the most recent Github version ?

https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3

**Comment by machasins** [comment]
I can confirm that this is happening with the most recent version.

**Comment by sakura-ryoko** [comment]
Try it with 1.21.3.

**Comment by machasins** [comment]
![javaw_G3XUIA6bDy](https://github.com/user-attachments/assets/c141a27e-02f4-4e00-ab3b-ae478c5fee07)


This issue has been resolved with this update, thanks!
