### ISSUE TITLE
Recipe book does not show recipe when selecing an item that is not currently craftable

### ISSUE THREAD

**Issue by RylanBueckert** [sakura-ryoko/itemscroller#26]
When clicking on a recipe in the recipe book that you do not have the items for, recipe should be displayed in the crafting grid like this:

![{D541474F-FA44-4875-8C6F-B98EF53E9D23}](https://github.com/user-attachments/assets/5b252c44-24a0-4613-81c9-5dfcf0a8fcaa)

Instead nothing is shown

**Version**
1.21.3-0.25.0-sakura.2

Seems to work with 1.21.1-0.24.50

**Comment by sakura-ryoko** [comment]
Mojang changed lots of of the Crafting code in Vanilla for 1.21.2/3 +, so it wouldn't surprise me if this is a change from Vanilla.

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21.3-0.25.0-sakura.3
