### ISSUE TITLE
[Suggestion] Backport features added in 1.21.3-0.25.0-sakura.6 to 1.21

### ISSUE THREAD

**Issue by ARedstoneMan** [sakura-ryoko/itemscroller#30]
Pretty self explanitory. I would like to see things like `massCraftToggle` and other crafting features added in this version ported to the 1.21 mod versions. I don't know if this is already being worked on, but I would like to see 1.21 still be maintained, as I still play this version regularly.

**Comment by sakura-ryoko** [comment]
I've already ported lots of features to 1.21, and my work with 1.21 is not finished.  There are some limitations as to what features I can backport, but I have already backported lots of features across the masa mod ecosystem from my 1.21.3+ branches.

**Comment by sakura-ryoko** [comment]
See Modrinth Release --> https://modrinth.com/mod/item-scroller/version/0.24.53
