### ISSUE TITLE
鼠标中键崩溃

### ISSUE THREAD

**Issue by BlackRiceXY** [sakura-ryoko/itemscroller#5]
[latest.log](https://github.com/user-attachments/files/16338908/latest.log)

**Comment by sakura-ryoko** [comment]
You have a lot of mods that are incompatible with each other.

**Comment by zly2006** [comment]
感谢反馈，我已经知道bug在哪了

同时哥们你注意一下个人隐私ok？这么大段日志也不处理就直接发，难绷

Thanks for reporting, I've found out this bug, fixing it soon.

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-sakura.7
