### ISSUE TITLE
Add ModPack licensing & Post to Modrinth suggestions

### ISSUE THREAD

**Issue by is52hertz** [sakura-ryoko/itemscroller#7]
I'm Trickly-Triple's modpack author.

I would like to add including this mod to my modpack, is this ok?
_I know where I can look it up, but I thought it would be easier to ask?_

And wanted to ask if there are any plans to release it at Modrinth. My ModPack is released in Modrinth, so in that case it will recognize your Mod!

_Translated by DeepL & Google_

**Comment by sakura-ryoko** [comment]
Masa will be releasing them to Modrinth sooner or later.
