### ISSUE TITLE
[suggestion]more sorting

### ISSUE THREAD

**Issue by pizzav-xyz** [sakura-ryoko/itemscroller#8]
allow to sort into columns, rows and regular

**Comment by alien-sunset** [comment]
also allowing to lock certain slots of the player inventory so that they will not get sorted would be lovely

**Comment by sakura-ryoko** [comment]
Additional fixes:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.3
